
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Natalie
 */
public class addStudent extends javax.swing.JFrame {

    /**
     * Creates new form addStudent
     */
    String dbURL = "jdbc:oracle:thin:@localhost:1521:orcl";
    String userN= "system";
    String passW = "Admin123";
    
    
    Connection conn = null;
    Statement stmt = null;
    
    public addStudent() {
        super("Add Student");
        initComponents();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
     public void clearFields(){
        id.setText(null);
        textfieldname.setText(null);
        textfieldFname.setText(null);
        textfieldcity.setText(null);
        textfieldphone.setText(null);
        textfieldclass.setText(null);
    
       }
    
    
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Name = new javax.swing.JLabel();
        FName = new javax.swing.JLabel();
        City = new javax.swing.JLabel();
        Blood = new javax.swing.JLabel();
        Phone = new javax.swing.JLabel();
        Class = new javax.swing.JLabel();
        textfieldname = new javax.swing.JTextField();
        textfieldFname = new javax.swing.JTextField();
        textfieldcity = new javax.swing.JTextField();
        textfieldphone = new javax.swing.JTextField();
        textfieldclass = new javax.swing.JTextField();
        bloodcombobox = new javax.swing.JComboBox<>();
        submitbutton = new javax.swing.JButton();
        backbutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        HomeShortcut = new javax.swing.JMenuItem();
        LogoutShortcut = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Add Student", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 18), new java.awt.Color(153, 255, 153))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(153, 255, 153));

        Name.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        Name.setForeground(new java.awt.Color(153, 255, 153));
        Name.setText("Name");

        FName.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        FName.setForeground(new java.awt.Color(153, 255, 153));
        FName.setText("Father's Name");

        City.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        City.setForeground(new java.awt.Color(153, 255, 153));
        City.setText("City");

        Blood.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        Blood.setForeground(new java.awt.Color(153, 255, 153));
        Blood.setText("Blood");

        Phone.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        Phone.setForeground(new java.awt.Color(153, 255, 153));
        Phone.setText("Phone");

        Class.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        Class.setForeground(new java.awt.Color(153, 255, 153));
        Class.setText("Class");

        textfieldcity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldcityActionPerformed(evt);
            }
        });

        textfieldphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldphoneActionPerformed(evt);
            }
        });

        bloodcombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "A-", "A+", "B-", "B+", "AB" }));

        submitbutton.setBackground(new java.awt.Color(240, 240, 87));
        submitbutton.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        submitbutton.setText("Submit");
        submitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbuttonActionPerformed(evt);
            }
        });

        backbutton.setBackground(new java.awt.Color(240, 240, 87));
        backbutton.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        backbutton.setText("Back");
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 153));
        jLabel1.setText("Student ID");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Blood)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Name)
                            .addComponent(FName)
                            .addComponent(Phone)
                            .addComponent(City)
                            .addComponent(Class)
                            .addComponent(jLabel1))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textfieldname)
                                    .addComponent(textfieldFname)
                                    .addComponent(textfieldcity)
                                    .addComponent(textfieldclass)
                                    .addComponent(bloodcombobox, 0, 194, Short.MAX_VALUE)
                                    .addComponent(id)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textfieldphone, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submitbutton)
                .addGap(114, 114, 114)
                .addComponent(backbutton)
                .addGap(55, 55, 55))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textfieldname, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Name))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textfieldFname, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FName))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(City)
                    .addComponent(textfieldcity, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Blood)
                    .addComponent(bloodcombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textfieldphone, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Phone))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textfieldclass, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Class))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(submitbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(backbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        HomeShortcut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        HomeShortcut.setText("Home");
        HomeShortcut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeShortcutActionPerformed(evt);
            }
        });
        jMenu1.add(HomeShortcut);

        LogoutShortcut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        LogoutShortcut.setText("Logout");
        LogoutShortcut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutShortcutActionPerformed(evt);
            }
        });
        jMenu1.add(LogoutShortcut);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(529, 605));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textfieldcityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldcityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldcityActionPerformed

    private void textfieldphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldphoneActionPerformed

    private void HomeShortcutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeShortcutActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        home object = new home();
        object.setVisible(true);
    }//GEN-LAST:event_HomeShortcutActionPerformed

    private void LogoutShortcutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutShortcutActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        login object = new login();
        object.setVisible(true);
    }//GEN-LAST:event_LogoutShortcutActionPerformed

    private void submitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbuttonActionPerformed
        // TODO add your handling code here:
            int stdId = Integer.parseInt(id.getText());
            String stdName = textfieldname.getText();
            String stdBlood = (String) bloodcombobox.getSelectedItem();
            String stdFatherName = textfieldFname.getText();
            String stdCity = textfieldcity.getText();
            String stdPhone = textfieldphone.getText();
            int stdclass = Integer.parseInt(textfieldclass.getText());
        
        try{
            conn = DriverManager.getConnection(dbURL, userN, passW);
            stmt = conn.createStatement();
            
          
            
            String sql = "INSERT INTO student(id, stdName, stdBlood, stdFatherName, stdCity, stdPhone, class) VALUES('"+stdId+"', '"+stdName+"', '"+stdBlood+"', '"+stdFatherName+"', '"+stdCity+"', '"+stdPhone+"', '"+stdclass+"')";
      
            stmt.executeUpdate(sql);
              JOptionPane.showMessageDialog(null, "Data is successfully inserted");
               clearFields();
              
              conn.close();
              
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_submitbuttonActionPerformed

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
       
        setVisible(false);
        home object = new home();
        object.setVisible(true);
    }//GEN-LAST:event_backbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Blood;
    private javax.swing.JLabel City;
    private javax.swing.JLabel Class;
    private javax.swing.JLabel FName;
    private javax.swing.JMenuItem HomeShortcut;
    private javax.swing.JMenuItem LogoutShortcut;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Phone;
    private javax.swing.JButton backbutton;
    private javax.swing.JComboBox<String> bloodcombobox;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton submitbutton;
    private javax.swing.JTextField textfieldFname;
    private javax.swing.JTextField textfieldcity;
    private javax.swing.JTextField textfieldclass;
    private javax.swing.JTextField textfieldname;
    private javax.swing.JTextField textfieldphone;
    // End of variables declaration//GEN-END:variables
}
