
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Natalie
 */
public class admin extends javax.swing.JFrame {

    /**
     * Creates new form admin
     */
    
     String dbURL = "jdbc:oracle:thin:@localhost:1521:orcl";
    String userN= "system";
    String passW = "Admin123";
    
    
    Connection conn = null;
    Statement stmt = null;
     ResultSet rs = null;
    
    
    public admin() {
        initComponents();
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
     public void clearFields(){
        id.setText(null);
        textfieldname.setText(null);
        textfieldemail.setText(null);
        passwordfield.setText(null);
    
       }
    
    
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textfieldname = new javax.swing.JTextField();
        textfieldemail = new javax.swing.JTextField();
        passwordfield = new javax.swing.JPasswordField();
        updatebutton = new javax.swing.JButton();
        backbutton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        searchbutton = new javax.swing.JButton();
        deletebutton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        HomeShortcut = new javax.swing.JMenuItem();
        LogoutShortcut = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Admin", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 3, 18), new java.awt.Color(153, 255, 153))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 153));
        jLabel1.setText("Name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 255, 153));
        jLabel2.setText("Email");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 255, 153));
        jLabel3.setText("Password");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));
        jPanel1.add(textfieldname, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 170, 30));
        jPanel1.add(textfieldemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 170, 30));
        jPanel1.add(passwordfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 170, 30));

        updatebutton.setBackground(new java.awt.Color(240, 240, 87));
        updatebutton.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        updatebutton.setText("Update");
        updatebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebuttonActionPerformed(evt);
            }
        });
        jPanel1.add(updatebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 100, -1));

        backbutton.setBackground(new java.awt.Color(240, 240, 87));
        backbutton.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        backbutton.setText("Back");
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(backbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 90, -1));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 255, 153));
        jLabel4.setText("ID");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 50, -1));
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 170, 30));

        searchbutton.setBackground(new java.awt.Color(240, 240, 87));
        searchbutton.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        searchbutton.setText("Search");
        searchbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(searchbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 100, -1));

        deletebutton.setBackground(new java.awt.Color(240, 240, 87));
        deletebutton.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        deletebutton.setText("Delete");
        deletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebuttonActionPerformed(evt);
            }
        });
        jPanel1.add(deletebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 90, -1));

        jMenu1.setText("Admin Management");

        HomeShortcut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        HomeShortcut.setText("Home");
        HomeShortcut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeShortcutActionPerformed(evt);
            }
        });
        jMenu1.add(HomeShortcut);

        LogoutShortcut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        LogoutShortcut.setText("Logout");
        LogoutShortcut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutShortcutActionPerformed(evt);
            }
        });
        jMenu1.add(LogoutShortcut);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updatebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebuttonActionPerformed
        // TODO add your handling code here:
       int stdId = Integer.parseInt(id.getText());
        
        String adminName = textfieldname.getText();
        String adminMail = textfieldemail.getText();
        String adminPass = passwordfield.getText();

        try {

            conn = DriverManager.getConnection(dbURL, userN, passW);
            stmt = conn.createStatement();
            
            String sql = "UPDATE accounts SET name ='"+adminName+"', email='"+adminMail+"', password='"+adminPass+"' WHERE admin_id = " + stdId;


            stmt.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Data inserted successfully");
            clearFields();
            conn.close();
        }catch (Exception e){JOptionPane.showMessageDialog(null, e);
    }//GEN-LAST:event_updatebuttonActionPerformed
    }
    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        home object = new home();
        object.setVisible(true);
    }//GEN-LAST:event_backbuttonActionPerformed

    private void HomeShortcutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeShortcutActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        home object = new home();
        object.setVisible(true);
    }//GEN-LAST:event_HomeShortcutActionPerformed

    private void LogoutShortcutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutShortcutActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        login object = new login();
        object.setVisible(true);
    }//GEN-LAST:event_LogoutShortcutActionPerformed

    private void searchbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbuttonActionPerformed

        
        
         int stdId = Integer.parseInt(id.getText());
         
         try{
            conn = DriverManager.getConnection(dbURL, userN, passW);
             PreparedStatement ps = conn.prepareStatement("SELECT * FROM accounts WHERE admin_id = '"+stdId+"'");
             ResultSet rs = ps.executeQuery();
            
            if(rs.next()){
            
            textfieldname.setText(rs.getString("name"));
            textfieldemail.setText(rs.getString("email"));
            passwordfield.setText(rs.getString("password"));
           
            
        }
            else{  
                    JOptionPane.showMessageDialog(null, "Record Not Found");
                
                }
                  
        }catch (Exception e){JOptionPane.showMessageDialog(null,e);
        
        
    }//GEN-LAST:event_searchbuttonActionPerformed
    }
    private void deletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebuttonActionPerformed
        int stdId = Integer.parseInt(id.getText());
        try {
          
        conn = DriverManager.getConnection(dbURL, userN, passW);
        stmt = conn.createStatement();

        String sql = "DELETE FROM accounts WHERE admin_id = " + stdId;
        int dialogResult = JOptionPane.showConfirmDialog (null, "Would you like to delete this record?");
        if(dialogResult == JOptionPane.YES_OPTION){
        stmt.executeUpdate(sql);
        
        
        JOptionPane.showMessageDialog(null, "Deleted successfully....");
        clearFields();
        
        }
        conn.close();
        setVisible(false);
                showAdmin object = new showAdmin();
                object.setVisible(true);
        
        
            
        }catch (Exception e){JOptionPane.showMessageDialog(null,e);
        
        
    }//GEN-LAST:event_deletebuttonActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem HomeShortcut;
    private javax.swing.JMenuItem LogoutShortcut;
    private javax.swing.JButton backbutton;
    private javax.swing.JButton deletebutton;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField passwordfield;
    private javax.swing.JButton searchbutton;
    private javax.swing.JTextField textfieldemail;
    private javax.swing.JTextField textfieldname;
    private javax.swing.JButton updatebutton;
    // End of variables declaration//GEN-END:variables
}
