
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Natalie
 */
public class student extends javax.swing.JFrame {

   
    String dbURL = "jdbc:oracle:thin:@localhost:1521:orcl";
    String userN= "system";
    String passW = "Admin123";
    
    
    Connection conn = null;
    Statement stmt = null;
    
    
//     Connection conn = null;
//    Statement stmt = null;
    ResultSet rs = null;
    
    public student() {
        super("Students");
        initComponents();
        this.setLocationRelativeTo(null);
//        conn = databaseConnection.connection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
     public void clearFields(){
        id.setText(null);
        textfieldname.setText(null);
        textfieldFname.setText(null);
        textfieldcity.setText(null);
        textfieldphone.setText(null);
        textfieldclass.setText(null);
    
       }
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Id = new javax.swing.JLabel();
        FName = new javax.swing.JLabel();
        City = new javax.swing.JLabel();
        Blood = new javax.swing.JLabel();
        Phone = new javax.swing.JLabel();
        Class = new javax.swing.JLabel();
        textfieldname = new javax.swing.JTextField();
        textfieldFname = new javax.swing.JTextField();
        textfieldcity = new javax.swing.JTextField();
        textfieldphone = new javax.swing.JTextField();
        textfieldclass = new javax.swing.JTextField();
        updatebutton = new javax.swing.JButton();
        backbutton = new javax.swing.JButton();
        searchbutton = new javax.swing.JButton();
        deletebutton = new javax.swing.JButton();
        textfieldblood = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        Name1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        HomeShortcut = new javax.swing.JMenuItem();
        LogoutShortcut = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Student Record", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 3, 18), new java.awt.Color(153, 255, 153))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(153, 255, 153));
        jPanel1.setToolTipText("");

        Id.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        Id.setForeground(new java.awt.Color(153, 255, 153));
        Id.setText("Id");

        FName.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        FName.setForeground(new java.awt.Color(153, 255, 153));
        FName.setText("Father's Name");

        City.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        City.setForeground(new java.awt.Color(153, 255, 153));
        City.setText("City");

        Blood.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        Blood.setForeground(new java.awt.Color(153, 255, 153));
        Blood.setText("Blood");

        Phone.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        Phone.setForeground(new java.awt.Color(153, 255, 153));
        Phone.setText("Phone");

        Class.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        Class.setForeground(new java.awt.Color(153, 255, 153));
        Class.setText("Class");

        textfieldFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldFnameActionPerformed(evt);
            }
        });

        textfieldcity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldcityActionPerformed(evt);
            }
        });

        textfieldphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldphoneActionPerformed(evt);
            }
        });

        updatebutton.setBackground(new java.awt.Color(240, 240, 87));
        updatebutton.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        updatebutton.setText("Update");
        updatebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebuttonActionPerformed(evt);
            }
        });

        backbutton.setBackground(new java.awt.Color(240, 240, 87));
        backbutton.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        backbutton.setText("Back");
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });

        searchbutton.setBackground(new java.awt.Color(240, 240, 87));
        searchbutton.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        searchbutton.setText("Search");
        searchbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbuttonActionPerformed(evt);
            }
        });

        deletebutton.setBackground(new java.awt.Color(240, 240, 87));
        deletebutton.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        deletebutton.setText("Delete");
        deletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebuttonActionPerformed(evt);
            }
        });

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });

        Name1.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        Name1.setForeground(new java.awt.Color(153, 255, 153));
        Name1.setText("Name");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Id)
                    .addComponent(FName)
                    .addComponent(Phone)
                    .addComponent(City)
                    .addComponent(Class)
                    .addComponent(Blood)
                    .addComponent(Name1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textfieldblood, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textfieldphone, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textfieldclass, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(textfieldcity, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                                .addComponent(id, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textfieldFname)
                                .addComponent(textfieldname)))
                        .addContainerGap(108, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(searchbutton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(updatebutton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(deletebutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(backbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Id))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textfieldname, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Name1))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FName, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(textfieldFname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(City)
                                    .addComponent(textfieldcity, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Blood)
                                    .addComponent(textfieldblood, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addComponent(textfieldphone, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Phone))
                        .addGap(44, 44, 44)
                        .addComponent(textfieldclass, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Class))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updatebutton)
                    .addComponent(backbutton))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchbutton)
                    .addComponent(deletebutton))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jMenu1.setText("Student Management");

        HomeShortcut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        HomeShortcut.setText("Home");
        HomeShortcut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeShortcutActionPerformed(evt);
            }
        });
        jMenu1.add(HomeShortcut);

        LogoutShortcut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        LogoutShortcut.setText("Logout");
        LogoutShortcut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutShortcutActionPerformed(evt);
            }
        });
        jMenu1.add(LogoutShortcut);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textfieldcityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldcityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldcityActionPerformed

    private void textfieldphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldphoneActionPerformed

    private void updatebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebuttonActionPerformed
        // TODO add your handling code here:
         int stdId = Integer.parseInt(id.getText());
        String stdName = textfieldname.getText();
            String stdBlood = textfieldblood.getText();
            String stdFatherName = textfieldFname.getText();
            String stdCity = textfieldcity.getText();
            String stdPhone = textfieldphone.getText();
            int stdclass = Integer.parseInt(textfieldclass.getText());
        try{
            conn = DriverManager.getConnection(dbURL, userN, passW);
           stmt = conn.createStatement();
            

            String sql = "UPDATE student SET stdName ='"+stdName+"', stdFatherName='"+stdFatherName+"', stdBlood ='"+stdBlood+"', stdCity ='"+stdCity+"', stdPhone ='"+stdPhone+"', class  ='"+stdclass+"' WHERE id = " + stdId;

            stmt.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Data is successfully updated");
            conn.close();
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_updatebuttonActionPerformed

    private void searchbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbuttonActionPerformed
    
        
         int stdId = Integer.parseInt(id.getText());
         
         try{
            conn = DriverManager.getConnection(dbURL, userN, passW);
             PreparedStatement ps = conn.prepareStatement("SELECT * FROM STUDENT WHERE id = '"+stdId+"'");
             ResultSet rs = ps.executeQuery();
            
            if(rs.next()){
            
            textfieldname.setText(rs.getString("stdName"));
            textfieldFname.setText(rs.getString("stdFatherName"));
            textfieldblood.setText(rs.getString("stdBlood"));
            textfieldcity.setText(rs.getString("stdCity"));
            textfieldphone.setText(rs.getString("stdPhone"));
            textfieldclass.setText(String.format("%s", rs.getInt("class")));
            
        }
            else{  
                    JOptionPane.showMessageDialog(null, "Record Not Found");
                
                }
                  
        }catch (Exception e){JOptionPane.showMessageDialog(null,e);
        
        
    }//GEN-LAST:event_searchbuttonActionPerformed
    }
    private void deletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebuttonActionPerformed
        // TODO add your handling code here:
               int stdId = Integer.parseInt(id.getText());
        try {
          
        conn = DriverManager.getConnection(dbURL, userN, passW);
        stmt = conn.createStatement();

        String sql = "DELETE FROM student WHERE id = " + stdId;
        int dialogResult = JOptionPane.showConfirmDialog (null, "Would you like to delete this record?");
        if(dialogResult == JOptionPane.YES_OPTION){
        stmt.executeUpdate(sql);
        
        
        JOptionPane.showMessageDialog(null, "Deleted successfully....");
        clearFields();
        
        }
        conn.close();
        setVisible(false);
                showStudent object = new showStudent();
                object.setVisible(true);
        
        
            
        }catch (Exception e){JOptionPane.showMessageDialog(null,e);
    }//GEN-LAST:event_deletebuttonActionPerformed
    }
    private void textfieldFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldFnameActionPerformed

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
                home object = new home();
                object.setVisible(true);
    }//GEN-LAST:event_backbuttonActionPerformed

    private void HomeShortcutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeShortcutActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        home object = new home();
        object.setVisible(true);
    }//GEN-LAST:event_HomeShortcutActionPerformed

    private void LogoutShortcutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutShortcutActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        login object = new login();
        object.setVisible(true);
    }//GEN-LAST:event_LogoutShortcutActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Blood;
    private javax.swing.JLabel City;
    private javax.swing.JLabel Class;
    private javax.swing.JLabel FName;
    private javax.swing.JMenuItem HomeShortcut;
    private javax.swing.JLabel Id;
    private javax.swing.JMenuItem LogoutShortcut;
    private javax.swing.JLabel Name1;
    private javax.swing.JLabel Phone;
    private javax.swing.JButton backbutton;
    private javax.swing.JButton deletebutton;
    private javax.swing.JTextField id;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton searchbutton;
    private javax.swing.JTextField textfieldFname;
    private javax.swing.JTextField textfieldblood;
    private javax.swing.JTextField textfieldcity;
    private javax.swing.JTextField textfieldclass;
    private javax.swing.JTextField textfieldname;
    private javax.swing.JTextField textfieldphone;
    private javax.swing.JButton updatebutton;
    // End of variables declaration//GEN-END:variables
}
